env:
  global:
    - CODECOV_TOKEN="1c776415-4f87-41d6-9078-d911bb2f9a2f" # https://codecov.io

language: node_js

node_js:
  - 10

# not recuired as of 2016(?)
# before_script:
#  - npm install grunt-cli -g

script:
  - npm run test     # get the tests run before building
  - npm run coverage # get the coverage run before building
  - npm run build    # we have a build badge, so run the build
